import Navbar from "./components/Navbar";
import Sparks from "./components/Sparks";
import Footer from "./components/Footer";
import "./globals.css";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import { ModalContextProvider } from "./context/modal";
import { Modal } from "./components/Modal";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});
const KafuTechnoStd = localFont({
  src: "./fonts/FOT-KafuTechnoStd-H.otf",
  variable: "--font-KafuTechnoStd",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
        {/* <script src="/lib/createjs.min.js" async />
        <script src="/lib/particlejs.min.js" async /> */}
      </head>
      <ModalContextProvider>
        <body className={`min-h-[100vh] ${roboto.variable} ${KafuTechnoStd.variable}`}>
          <div className="fixed inset-0 bg-gradient-to-b from-[#000305] via-[#000305] to-[#130316] z-0" />
          <Sparks />
          <div className="fixed inset-0 master-duel-screen-texture z-0" />
          <Navbar />
          <Modal />
          <div className="relative px-2 z-1 lg:px-8 py-16 lg:py-24 min-h-[calc(100vh-70px)] max-w-[1800px] mx-auto text-slate-200">
            <main>{children}</main>
          </div>
          <Footer />
        </body>
      </ModalContextProvider>
    </html>
  );
}
